// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UsuarioApp.Modelo
{
    public partial class Pantalla
    {
        public Pantalla()
        {
            RolPantalla = new HashSet<RolPantalla>();
        }

        public int IdPantalla { get; set; }
        public string Descripcion { get; set; }
        public string PathUrl { get; set; }
        public string Icono { get; set; }
        public int? IdPantallaPadre { get; set; }
        public int Orden { get; set; }
        public bool RegistroVigente { get; set; }

        public virtual ICollection<RolPantalla> RolPantalla { get; set; }
    }
}