// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UsuarioApp.Modelo
{
    public partial class RolPantalla
    {
        public int IdRolPantalla { get; set; }
        public int IdPantalla { get; set; }
        public int IdRol { get; set; }

        public virtual Pantalla IdPantallaNavigation { get; set; }
        public virtual Rol IdRolNavigation { get; set; }
    }
}